version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: ./swagger/swagger.json
    ports:
      - '8080:8080'
  back:
    build:
      context: back
    ports:
      - "8081:8081"
  front:
    build:
      context: front
    ports:
      - "80:8080"