version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: ./swagger/swagger.json
    ports:
      - '8001:8080'